Issue #91, TypeError: this.fail is not a function
When there is 'error' in the response, passport should call this.fail instead of this.error. The difference is:
(1) this.error is for server error
(2) this.fail is for authentication error, where the server has no problem. In this case, the server can redirect the user to login page (or whatever page the developer sets) for authentication.